name: Dev CI

on:
  push:
    branches:
      - dev
      - feature/**
  pull_request:
    branches:
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest

      - name: Run unit tests
        run: |
          export PYTHONPATH=$PYTHONPATH:$(pwd)/src
          pytest tests/ -v
