name: Dev CI

on:
  push:
    branches:
      - dev
      - feature/**
  pull_request:
    branches:
      - dev

jobs:
  build-test:
    runs-on: ubuntu-latest

    steps:
      # 1️⃣ Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # 2️⃣ Set up Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: "3.11"

      # 3️⃣ Cache pip dependencies
      - name: Cache pip
        uses: actions/cache@v3
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}
          restore-keys: |
            ${{ runner.os }}-pip-

      # 4️⃣ Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
          pip install pytest flake8 mypy
          pip install -e .

      # 5️⃣ Set PYTHONPATH so imports work
      - name: Set PYTHONPATH
        run: echo "PYTHONPATH=$PYTHONPATH:$(pwd)/src" >> $GITHUB_ENV

      # 6️⃣ Run linting
      - name: Lint code
        run: flake8 src tests

      # 7️⃣ Run type checking
      - name: Type check
        run: mypy src

      # 8️⃣ Run unit tests
      - name: Run unit tests
        run: pytest tests/ -v
